"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const path_1 = __importDefault(require("path"));
const userRoute_1 = __importDefault(require("./routes/userRoute"));
const productGroupRoute_1 = __importDefault(require("./routes/productGroupRoute"));
const productRoute_1 = __importDefault(require("./routes/productRoute"));
const productVariantRoute_1 = __importDefault(require("./routes/productVariantRoute"));
const supplierRoute_1 = __importDefault(require("./routes/supplierRoute"));
const importReceiptRoute_1 = __importDefault(require("./routes/importReceiptRoute"));
const debtProviderRoute_1 = __importDefault(require("./routes/debtProviderRoute"));
const invoiceRoute_1 = __importDefault(require("./routes/invoiceRoute"));
const exportStockRoute_1 = __importDefault(require("./routes/exportStockRoute"));
const lossStockRoute_1 = __importDefault(require("./routes/lossStockRoute"));
const cashFlowRoute_1 = __importDefault(require("./routes/cashFlowRoute"));
const reportRoute_1 = __importDefault(require("./routes/reportRoute"));
const affiliateCommissionRoute_1 = __importDefault(require("./routes/affiliateCommissionRoute"));
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use("/uploads", express_1.default.static(path_1.default.join(process.cwd(), "uploads")));
app.use("/users", userRoute_1.default);
app.use("/product-groups", productGroupRoute_1.default);
app.use("/products", productRoute_1.default);
app.use("/variants", productVariantRoute_1.default);
app.use("/suppliers", supplierRoute_1.default);
app.use("/import-receipts", importReceiptRoute_1.default);
app.use("/debt", debtProviderRoute_1.default);
app.use("/invoice", invoiceRoute_1.default);
app.use("/export-stock", exportStockRoute_1.default);
app.use("/loss-stock", lossStockRoute_1.default);
app.use("/cash-flow", cashFlowRoute_1.default);
app.use("/reports", reportRoute_1.default);
app.use("/affiliate-commissions", affiliateCommissionRoute_1.default);
app.listen(3000, () => { console.log("Server chạy tại http://localhost:3000"); });
//# sourceMappingURL=index.js.map